# Generated by Django 4.1 on 2022-11-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monthly_sales_report',
        ),
        migrations.DeleteModel(
            name='sales_report',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
